### ISSUE TITLE
Delco E78

### ISSUE THREAD

**Issue by hapvlz** [joukoy/UniversalPatcher#1]
Hello,

is the project still supported? Does it support Delco E78?

Great job!
Thanks.

**Comment by joukoy** [comment]
Hello.

Project is under active development.
Initial support for E78: Replace file dtcsearch.xml in folder XML with this.
[DtcSearch.zip](https://github.com/joukoy/UniversalPatcher/files/6382908/DtcSearch.zip)

**Comment by hapvlz** [comment]
Thank you.

Is there maybe some kind of documentation how to use it?
I've replaced the file, opened the app, selected the ecu bin file, went into category "File info", selected only Search DTC, then Find all. And the scan never ends.

**Comment by joukoy** [comment]
There is no documentation, sorry.
Try this: Click "Tuner"
In Tuner window: File -> Open BIN
After this you should have one table available: DTC, and you can edit it.
