### ISSUE TITLE
Problem with P01

### ISSUE THREAD

**Issue by Sudsy55** [joukoy/UniversalPatcher#3]
G'day,
I can't seem to get it to open bin files that i have saved in ls droid. I just get the following message. I am using cable from OBDX proGt which doesn't seem to work with PCM Hammer at the moment either. Works fine with LS Droid and Tuner pro.
Cheers and thanks

Error, frmTuner , line 0: C:\Users\HP\Desktop\Icons\explorer.ico
Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
Importing tableseek...Seeking tables...
Importing TableSeek tables...  [OK]
Importing DTC codes...DTC search: can't find DTC code table
 [OK]

**Comment by joukoy** [comment]
Looks like you are running it directly from zip package, or you have only
.exe ?
Please download file: UniversalPatcher-Full.Zip
and extract all files to new, empty folder, then run from there.

**Comment by Sudsy55** [comment]
Thanks joukoy, 
Thanks mate. I extracted it again and it works fine now. Thanks again
